import type { Metadata } from "next";
import { Geist, DM_Sans } from "next/font/google";
import './../style/globals.css';

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const dm_sans = DM_Sans({
  variable: "--dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${dm_sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
