import type { Metadata } from "next";
import { Happy_Monkey } from "next/font/google";
import './../style/globals.css';

const happy_monkey = Happy_Monkey({
  variable: "--happy-monkey",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${happy_monkey.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
